apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent   #Always, Never
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
      hostPort: 81
  containers:
  - name: tomcat
    image: tomcat
    imagePullPolicy: IfNotPresent   #Always, Never
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
      hostPort: 8080
